---
- name: Standalone MySQL Installation
  hosts: all
  tasks:
     - name: Transfering MySQL install script
       copy: src=/etc/ansible/roles/mysql_install/mysql_install.sh dest=/tmp mode=0777

     - name: Transfering MySQL config script
       copy: src=/etc/ansible/roles/mysql_install/mysql_install_config.sh dest=/tmp mode=0777

    - name: Transfering MySQL Version file
      copy: src=/etc/ansible/roles/mysql_install/MYSQL_VERSION dest=/tmp mode=0777

     - name: Execute the Instalation script - MySQL
       command: sh /tmp/mysql_install.sh
       register: cmd_install
     - debug: msg="{{ cmd_install.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_install.stderr_lines|replace('\\t',' ') }}"

     - name: Execute the Config script - MySQL
       command: sh /tmp/mysql_install_config.sh
       register: cmd_config
     - debug: msg="{{ cmd_config.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_config.stderr_lines|replace('\\t',' ') }}"

     - name: Ansible delete - MySQL install script
       file:
         path: /tmp/mysql_install_config.sh
         state: absent

     - name: Ansible delete - MySQL config script
       file:
         path: /tmp/mysql_install.sh
         state: absent

     - name: Ansible delete - MySQL Version file
       file:
         path: /tmp/MYSQL_VERSION
         state: absent
