---
- name: Standalone MySQL Installation
  hosts: all
  tasks:
     - name: Transfering MySQL install script
       copy: src=mysql_install/mysql_install.sh dest=/tmp mode=0777

     - name: Transfering MySQL Configuration script
       copy: src=mysql_install/mysql_install_config.sh dest=/tmp mode=0777

     - name: Executing MySQL Instalation script
       command: "sh /tmp/mysql_install.sh {{ mysql_version }}"
       register: cmd_install
     - debug: msg="{{ cmd_install.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_install.stderr_lines|replace('\\t',' ') }}"

     - name: Executing MySQL Configuration script
       command: sh /tmp/mysql_install_config.sh
       register: cmd_config
     - debug: msg="{{ cmd_config.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_config.stderr_lines|replace('\\t',' ') }}"

     - name: Ansible delete - MySQL install script
       file:
         path: /tmp/mysql_install.sh
         state: absent

     - name: Ansible delete - MySQL config script
       file:
         path: /tmp/mysql_install_config.sh
         state: absent
